### ISSUE TITLE
主备机房切换后，console模块 health-check.log中一直报"java.lang.NullPointerException"

### ISSUE THREAD

**Issue by zouzc** [ctripcorp/x-pipe#267]
在同一台主机上模拟两个机房jq和oy，每个机房部署一个哨兵，端口分别为5000,5001，当从jq切换到oy时，redis master成功切换到oy机房的redis，但console模块中一直打印如下错误信息:

 且哨兵5001中配置 sentinel monitor cluster1s1 172.17.5.162 6579 3， 实质上每个机房只有一个哨兵，这儿的3是如何来的。 
在单机房中模拟master宕机，也会出现option_value设置为3，并且在宕机master重启后，无法自动成为新master的second

进程使用的是github上的二进制包.

[15:26:01:715][INFO][globalExecutor-1131101][DefaultSentinelHelloCollector][doAction][already exist]172.111.5.111:6579, 127.0.0.1:5001
[15:28:31:178][INFO][globalExecutor-1131351][DefaultSentinelHelloCollector][doAction][add][[stl: 127.0.0.1:5001, master: 172.111.5.111:6579, name:cluster1s1]]
[15:28:31:178][INFO][globalExecutor-1131351][DefaultSentinelHelloCollector][doAction][del][[stl: 172.111.5.111:5001, master: 172.111.5.111:6579, name:cluster1s1], [stl: 172.111.5.111:5000, master: 172.111.5.111:6379, name:cluster1s1]]
[15:28:31:179][ERROR][globalExecutor-1131350][SentinelCollector4Keeper][doAction] java.lang.NullPointerException
        at com.ctrip.xpipe.redis.console.healthcheck.actions.sentinel.SentinelCollector4Keeper$SentinelCollectorAction$3.doAction(SentinelCollector4Keeper.java:123) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.actions.sentinel.SentinelCollector4Keeper.doCollect(SentinelCollector4Keeper.java:51) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.actions.sentinel.SentinelCollector4Keeper.onAction(SentinelCollector4Keeper.java:64) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.actions.sentinel.SentinelCollector4Keeper.onAction(SentinelCollector4Keeper.java:25) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.AbstractHealthCheckAction$1.doRun(AbstractHealthCheckAction.java:89) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.concurrent.AbstractExceptionLogTask.run(AbstractExceptionLogTask.java:20) ~[core-1.0.0.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

[15:28:31:185][INFO][globalExecutor-1131351][DefaultSentinelHelloCollector][doAction][already exist]172.111.5.111:6579, 127.0.0.1:5001
[15:29:41:930][INFO][globalExecutor-1131462][ClientConfigMonitor][doCheck]
[15:29:41:934][WARN][globalExecutor-1131462][ClientConfigMonitor][checkCluster] com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.EqualsException: obj not shard:null
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.EqualsException.createShardException(EqualsException.java:36) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.CheckShard.equals(CheckShard.java:53) ~[redis-console-1.0.0.jar!/:?]
        at java.util.AbstractMap.equals(AbstractMap.java:495) ~[?:1.8.0_144]
        at com.ctrip.xpipe.utils.ObjectUtils.equals(ObjectUtils.java:28) ~[core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.CheckCluster.equals(CheckCluster.java:59) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.ClientConfigMonitor.checkCluster(ClientConfigMonitor.java:79) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.ClientConfigMonitor.doCheck(ClientConfigMonitor.java:54) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.AbstractIntervalCheck$2.doRun(AbstractIntervalCheck.java:82) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.concurrent.AbstractExceptionLogTask.run(AbstractExceptionLogTask.java:20) ~[core-1.0.0.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by wenchaomeng** [comment]
这个3是个默认值，系统默认至少配置三个哨兵，才能达到哨兵的高可用

**Comment by zouzc** [comment]
@wenchaomeng  这个值可以自定义配置吗？如果能自定义配置，具体调整那个配置的参数

**Comment by zouzc** [comment]
@wenchaomeng  如果每次切换时都会将这quorum 默认设置为3，而哨兵恰好是3，只要一个哨兵宕了，就无法实现故障转移了。

**Comment by wenchaomeng** [comment]
至少三个哨兵，生产环境单机房部署5个；建议按照标准部署部署哨兵，目前暂时不支持配置修改
