### ISSUE TITLE
console的health-check.log重复出现"com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.EqualsException: obj not shard:null"

### ISSUE THREAD

**Issue by zouzc** [ctripcorp/x-pipe#271]
使用github下载的1.0.0版本xpipe在单机上模拟两个机房，console中health-check.log频繁出现以下告警,在console告警中加入日志输出,发现告警产生的集群名为null。
private void checkCluster(String clusterName, XpipeMeta xpipeMeta) throws Exception {
    OuterClientService.ClusterInfo clusterInfo = outerClientService.getClusterInfo(clusterName);
    logger.info("[checkCluster],clusterName:",clusterName," info:",clusterInfo);
加入调试日志的输出:
[16:26:48:908][INFO][globalExecutor-482][ClientConfigMonitor][doCheck]
[16:26:48:908][INFO][globalExecutor-482][ClientConfigMonitor][doCheck]xpipeMeta:
[16:26:48:910][INFO][globalExecutor-482][ClientConfigMonitor][checkCluster],clusterName:
[16:26:48:939][INFO][globalExecutor-482][ClientConfigMonitor][checkCluster],checkClusterInfo:

原始日志输出:
[14:38:09:101][INFO][globalExecutor-692122][ClientConfigMonitor][doCheck]
[14:38:09:106][WARN][globalExecutor-692122][ClientConfigMonitor][checkCluster] com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.EqualsException: obj not shard:null
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.EqualsException.createShardException(EqualsException.java:36) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.CheckShard.equals(CheckShard.java:53) ~[redis-console-1.0.0.jar!/:?]
        at java.util.AbstractMap.equals(AbstractMap.java:495) ~[?:1.8.0_144]
        at com.ctrip.xpipe.utils.ObjectUtils.equals(ObjectUtils.java:28) ~[core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.CheckCluster.equals(CheckCluster.java:59) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.ClientConfigMonitor.checkCluster(ClientConfigMonitor.java:79) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.clientconfig.ClientConfigMonitor.doCheck(ClientConfigMonitor.java:54) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.console.healthcheck.nonredis.AbstractIntervalCheck$2.doRun(AbstractIntervalCheck.java:82) ~[redis-console-1.0.0.jar!/:?]
        at com.ctrip.xpipe.concurrent.AbstractExceptionLogTask.run(AbstractExceptionLogTask.java:20) ~[core-1.0.0.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by NickNYU** [comment]
这个是内部实现, 不应该跑的, 我最近抽时间修一下吧, 不应用主业务, 只是报错
