### ISSUE TITLE
 java.lang.IllegalStateException: ConfigGetDisklessSync result length not right:0

### ISSUE THREAD

**Issue by zouzc** [ctripcorp/x-pipe#285]
环境信息:
xpipe version: 1.0
操作系统: centos7.5
redis version:2.8.15
console日志目录 health-check.log出现大量如下日志
[11:14:34:108][ERROR][NettyKeyedPoolClientFactory-7][DiskLessReplCheckAction][DiskLessReplCheckAction]{} java.lang.IllegalStateException: ConfigGetDisklessSync result length not right:0
        at com.ctrip.xpipe.redis.core.protocal.cmd.ConfigGetCommand$ConfigGetDisklessSync.doFormat(ConfigGetCommand.java:83) ~[redis-core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.core.protocal.cmd.ConfigGetCommand$ConfigGetDisklessSync.doFormat(ConfigGetCommand.java:68) ~[redis-core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.core.protocal.cmd.ConfigGetCommand.format(ConfigGetCommand.java:33) ~[redis-core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.redis.core.protocal.cmd.AbstractRedisCommand.doReceiveResponse(AbstractRedisCommand.java:129) ~[redis-core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.netty.commands.AbstractNettyRequestResponseCommand.receive(AbstractNettyRequestResponseCommand.java:105) ~[core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.netty.commands.DefaultNettyClient.handleResponse(DefaultNettyClient.java:79) ~[core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.netty.commands.NettyClientHandler$1.read(NettyClientHandler.java:49) ~[core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.netty.RetryByteBufReadPolicy.read(RetryByteBufReadPolicy.java:33) ~[core-1.0.0.jar!/:?]
        at com.ctrip.xpipe.netty.commands.NettyClientHandler.channelRead(NettyClientHandler.java:45) ~[core-1.0.0.jar!/:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.28.Final.jar!/:4.1.28.Final]

**Comment by zouzc** [comment]
原因: redis 2.8.15 对于 config get repl-diskless-sync, 返回的是空。 所以导致上述异常抛出。
